### ISSUE TITLE
Update "Build your own navigator" docs for Navigation View API refactor

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#28]

**Comment by llamaluvr** [comment]
I was about to open an issue about documenting the new required `addListener` param for `addNavigationHelpers()` but then saw this. Would this issue includes the "Custom Navigators" (https://reactnavigation.org/docs/custom-navigators.html#addnavigationhelpers) docs and thus `addNavigationHelpers()`? With that additional information, we MobX folks should have enough to go on in order to integrate the new react-navigation with our stores. Thanks!

**Comment by ericvicenti** [comment]
this is what I've done so far: https://next.reactnavigation.org/docs/custom-navigators.html

Happy to hear feedback on this, or create more docs that you think are appropriate.
