### ISSUE TITLE
drawer-navigator.html definitely needs a link to react-native-gesture-handler doc

### ISSUE THREAD

**Issue by 4E71-NOP** [react-navigation/react-navigation.github.io#311]
Hello

https://reactnavigation.org/docs/en/drawer-navigator.html definitely needs a link to a page explaining how to implement "react-native-gesture-handler". Yes i know it's not your stuff. Let me explain.

If you create a new reactNative project and import scripts from an old project that was using V2. You will have to modify one thing or two. So far, nothing unusual.

Like :
using a container for the stack navigator (https://reactnavigation.org/docs/en/app-containers.html). This one is easy to find. 

But when it comes to the drawerMenu case; it becomes a little tricky.

You have to edit an Android file : MainActivity.java and implement the following:
```java
(some imports)
+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
```
as described here :
https://stackoverflow.com/questions/53394982/react-navigation-swipe-on-drawer-does-not-work-in-android

But this is the solution of the last problem. To get there you have to browse an absolutely non null number of pages.

- First you get the "Gesture Handler" errors. ->install & link react-native-gesture-handler
- Then, if it works; the drawer menu isn't showing when using a gesture.
- Then you search/test for hours what can be wrong, etc.
- Finally you get the Stack Overflow page mentioned before.

My point is : I was in the process of migrating my project. There's always a bug in the process, i'm fine with that. I checked the  drawer-navigator.html, and did not find any mention of gesture. If the drawer-navigator.html page warned me about the difference between V2 & V3 especially about Gesture; I would definitively have finished migrating it one or 2 days before. 

It doesn't have to be a big paragraph. Only to mention that this will be necessary and link to the page : https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html

**Comment by brentvatne** [comment]
this is in the installation process: https://reactnavigation.org/docs/en/getting-started.html#installation

however in the release notes i forgot to mention the android part of the process, this is because i am quite biased as i work on expo and tend to use it for most of the react-native development that i do, and this step isn't necessary with expo. i have updated the release notes to link directly to the react-native-gesture-handler installation steps in their docs

<img width="807" alt="screen shot 2018-11-27 at 12 35 06 pm" src="https://user-images.githubusercontent.com/90494/49109956-f3634c80-f240-11e8-924c-a3a36d50ee5c.png">

stack navigator on ios also depends on react-native-gesture-handler, and any other navigator may as well in the future, so i don't think it makes sense to include this in a single api reference. i apologize for the hassle it caused you to have an incomplete upgrade guide, i'll try to do better in the future.
