### ISSUE TITLE
install too many libraries and dont konw why

### ISSUE THREAD

**Issue by ouzhou** [react-navigation/react-navigation.github.io#575]
In a bare rn project, i should install 
- react-navigation
- react-native-reanimated 
- react-native-gesture-handler
- react-native-screens@^1.0.0-alpha.23

Not friendly for beginners because we don't know why to install these packages.

Npm tells me  `react-native-screens`  `react-native-gesture-handler` ` react-native-gesture-handler` is required, but i dont know react-native-reanimated is requied too? can we make the installation easier?

**Comment by ouzhou** [comment]
Does `react-native-reanimated ` have to be installed?

**Comment by JarnoNijhof** [comment]
Hi,
I know it's quite complex, but you will get used to it when you start making more projects.
Actually you need to install always such packages like;
navigations, stacknavigators gesture handler and so on...

The react-native-reanimated package provides a more comprehensive, low level abstraction for the Animated library API to be built on top of and hence allow for much greater flexibility especially when it comes to gesture based interactions.

I think you dont need to install it but it can be usefull.
You can try to do it without the reanimated package, when you dont get an error you're fine.

But remember that you can get errors from it later on in your project.

**Comment by artyorsh** [comment]
I know this is not the right place for posting this, but let me add my +1 for this conversation.
I was able to build a demo application that uses all navigators from new react-navigation. And here is a list of dependencies that needs to be installed

```json
{
  "@react-native-community/masked-view": "^0.1.5",
  "@react-navigation/bottom-tabs": "^5.0.0-alpha.22",
  "@react-navigation/core": "^5.0.0-alpha.23",
  "@react-navigation/drawer": "^5.0.0-alpha.23",
  "@react-navigation/material-top-tabs": "^5.0.0-alpha.18",
  "@react-navigation/native": "^5.0.0-alpha.16",
  "@react-navigation/stack": "^5.0.0-alpha.37",
  "react-native-gesture-handler": "^1.5.0",
  "react-native-reanimated": "^1.4.0",
  "react-native-screens": "^2.0.0-alpha.11"
}
```

I believe this can confuse the beginners and, actually, this list should be shortened if possible.

However, answering the @ouzhou question: `react-native-reanimated` [is used for better animations in stack navigators](https://blog.expo.io/re-writing-react-navigation-stack-db6a376522b1). Sometimes libraries need to peer dependencies rather than including it into own `package.json` dependencies because other libraries also rely on it. This is just like the case with `react-native-gessture-handler` or `react-native-svg` - you need these libraries in any React Native application.

**Comment by satya164** [comment]
reanimated is used to implement performant animations, gesture handler for native gestures, screens for improving memory usage, masked view is for implementing proper behavior for iOS header. last 2 things are optional, but metro doesn't support optional dependencies, so you need to install them. first two are because react native doesn't have any way to implement what we want in a performant way.

you need to install separate navigators based on the behavior you want because that lets you install only what you want, keeps bundle size small and we can release updates faster. most apps will use only 2-3 navigators.

we would make installation easier if we could.
