### ISSUE TITLE
Wrong Information about android hardware back button

### ISSUE THREAD

**Issue by dbrezack** [react-navigation/react-navigation.github.io#82]
[Doc](https://reactnavigation.org/docs/redux-integration.html#handling-the-hardware-back-button-in-android)
This Doc is wrong. 

ComponentWillMount and ComponentWillUnmount aren't guaranteed to be called when navigating between screens leaving extra listeners. 

Please see this issue [#298](https://github.com/react-navigation/react-navigation/issues/298) and this issue which was closed because of this issue [#51](https://github.com/react-navigation/react-navigation/issues/51)

**Comment by brentvatne** [comment]
cc @vonovak - perhaps we should change this to use `willBlur` / `willFocus`?

**Comment by brentvatne** [comment]
oh my bad, this is for the redux integration doc.

this is actually correct @dbrezack - you should only add it once on the root. react-navigation's root navigation container does the same thing (except in the constructor rather than componentWillMount)

you shouldn't add this to every screen. just the root screen as shown in the doc. perhaps it could be more clear about that? cc @Ashoat

**Comment by vonovak** [comment]
Then this guide is probably wrong: https://reactnavigation.org/docs/custom-android-back-button-handling.html

**Comment by dbrezack** [comment]
What about an instance which you want to goBack in some screens and do something custom in others ?  

@brentvatne You are right didn't see that it was in the AppNavigation component.
