### ISSUE TITLE
Clarification about documentation : Issue with using Actions to navigate in components and screens

### ISSUE THREAD

**Issue by KSR001** [react-navigation/react-navigation.github.io#886]
Hi,

I was going through the documentation on "Navigating without the navigation prop" and wanted a little clarification on "Do not use this method when you have access to a navigation prop or useNavigation since it will behave differently, and many helper methods specific to screens won't be available." [https://reactnavigation.org/docs/navigating-without-navigation-prop]

I looked at earlier version documentations, and this particular line has been recently added to the version 5.x docs. I actually wanted to use the method mentioned in the above documentation, from screens, and or components. I do understand that a service per se wouldn't allow the full range of capabilities supported when using the navigation prop in the screen. 

It would be great though if you could give some more clarification as to what could go wrong. So that we can be prepared accordingly.

We are planning to do something like this right now : 

public OpenDrawer(): void {
    if(navigatorReference.current)
       navigatorReference.current.dispatch(DrawerActions.openDrawer());    
  }

function NotificationsScreen({ navigation }: any) {
    return (
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }
        }>
            <Button onPress={() => navigationService.GoBack()} title="Go back home" />
            <Button onPress={() => navigationService.OpenDrawer()} title="Open Drawer"/>
            <Button onPress={() => navigationService.CloseDrawer()} title="Close Drawer"/>
            <Button onPress={() => navigationService.ToggleDrawer()} title="Toggle Drawer"/>
            <Button onPress={() => navigationService.JumpToScreenDrawer('home')} title="Jump to Drawer Home"/>
        </View>
    );
}

The whole code is available here : https://github.com/KSR001/NavigationWrapper

**Comment by satya164** [comment]
It's not possible to describe the differences in a straightforward way since each action might be implemented a bit differently depending on where it's called. However to summarize it in a more genral way: dispatching an action from the navigation prop in a screen makes sure that the action is always handled in the appropriate place, whereas dispatching actions from the root ref always dispatches the action to whatever the focused screen is, which may yield unexpected behaviour if you were expecting the focused screen to be different. There are also more complexities such as handling initiailization.

> We are planning to do something like this right now :

Don't do that. The `ref` isn't designed to be used everywhere, only where `navigation` prop isn't available such as redux middlewares. There's no reason to use it everywhere. You'll eventually need to use the `navigation` prop regardless since it's necessary for things like `setOptions` and end up with a mix of 2 patterns.
